parameters:
    xidea_dataflow.import.repository.default.class: Doctrine\ORM\EntityRepository
    xidea_dataflow.import.loader.default.class: Xidea\Bundle\DataflowBundle\Doctrine\ORM\Loader\ImportLoader
    xidea_dataflow.import.manager.default.class: Xidea\Bundle\DataflowBundle\Doctrine\ORM\Manager\ImportManager
  
services:
    xidea_dataflow.import.repository.default:
        class: %xidea_dataflow.import.repository.default.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %xidea_dataflow.import.class%
    xidea_dataflow.import.loader.default:
        class: %xidea_dataflow.import.loader.default.class%
        arguments:
            - @xidea_dataflow.import.repository.default
    xidea_dataflow.import.manager.default:
        class: %xidea_dataflow.import.manager.default.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @event_dispatcher
