parameters:
    xidea_dataflow.importer.default.class: Xidea\Bundle\DataflowBundle\Import\Importer
    xidea_dataflow.import.configuration.default.class: Xidea\Bundle\DataflowBundle\Configuration
    xidea_dataflow.import.factory.default.class: Xidea\Component\Dataflow\Factory\ProfileFactory
    xidea_dataflow.import.builder.default.class: Xidea\Component\Dataflow\Builder\ImportBuilder
  
services:
    xidea_dataflow.importer.default:
        class: %xidea_dataflow.importer.default.class%
        arguments:
            - @xidea_dataflow.import.configuration
    xidea_dataflow.import.configuration.default:
        class: %xidea_dataflow.import.configuration.default.class%
        arguments:
            - %xidea_dataflow.base_dir%
    xidea_dataflow.import.factory.default:
        class: %xidea_dataflow.import.factory.default.class%
        arguments:
            - %xidea_dataflow.import.class%
    xidea_dataflow.import.builder.default:
        class: %xidea_dataflow.import.builder.default.class%
        arguments:
            - @xidea_dataflow.import.factory