Xidea\Component\Dataflow\Model\AbstractProfile:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        context:
            type: string
            length: 64
        options:
            type: json_array